version: '3.8'

services:
  plex-renamer:
    build: .
    container_name: plex-media-renamer
    restart: unless-stopped
    ports:
      - "8080:5000"
    volumes:
      # Mount Plex media directory (REQUIRED - update path to your Plex media location)
      - ${PLEX_MEDIA_PATH:-./plex_media_data}:/media/plex:rw
      # Persistent configuration and logs
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      # Optional: Set timezone
      - TZ=${TZ:-UTC}
    networks:
      - plex-renamer-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  plex-renamer-net:
    driver: bridge

# Example of how to use with existing Plex setup
# If you have Plex running in Docker, you can share the same volume:
#
# volumes:
#   plex-media:
#     external: true  # If using external volume from Plex
#
# Then in the service:
#   volumes:
#     - plex-media:/media/plex:rw 